use math.sqrt in centrifugal distortion terms as np.sqrt blows up on long ints - with an unreasonable error message of AttributeError: 'int' object has no attribute 'sqrt' - see https://github.com/numpy/numpy/issues/368 for an discussion
Need to check performance implications of math.sqrt, though...